version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: ./devops/docker/node/Dockerfile
    image: backend_ws:latest
    command: bash -c "npm start"
    env_file:
      - .env
    ports:
      - 5002:5000
    volumes:
      - ../logs/taskman/ws_server/:/app/logs