version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: ./devops/docker/node/Dockerfile
    image: backend_ws:latest
    command: bash -c "npm start"
    env_file:
      - .env
    ports:
      - 5001:5000
    volumes:
      - ../logs/betting-app/ws_server/:/app/logs
    environment:
      WAIT_HOSTS: redis:6379
      WAIT_TIMEOUT: 60
  redis:
    image: 'redis'
    volumes:
      - ../redis-data-betting-app:/data
      - ../redis-betting-app/:/etc/redis/
    restart: "on-failure"